export const ROLE = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  JEFE_ENFERMERIA: 'JEFE_ENFERMERIA',
  ENFERMERO: 'ENFERMERO',
  RECEPCIONISTA: 'RECEPCIONISTA',
  MEDICO: 'MEDICO',
  TECNICO_FARMACIA: 'TECNICO_FARMACIA',
  CAJERO: 'CAJERO'
} as const;

export type Rol = (typeof ROLE)[keyof typeof ROLE];

export const ROLES_TODOS: Rol[] = [
  ROLE.ADMINISTRADOR,
  ROLE.JEFE_ENFERMERIA,
  ROLE.ENFERMERO,
  ROLE.RECEPCIONISTA,
  ROLE.MEDICO,
  ROLE.TECNICO_FARMACIA,
  ROLE.CAJERO
];

export const ROLES_ADMISION: Rol[] = [
  ROLE.ADMINISTRADOR,
  ROLE.JEFE_ENFERMERIA,
  ROLE.ENFERMERO,
  ROLE.RECEPCIONISTA
];

export const ROLES_ATENCION_MEDICA: Rol[] = [
  ROLE.ADMINISTRADOR,
  ROLE.MEDICO
];

export const ROLES_FARMACIA: Rol[] = [
  ROLE.ADMINISTRADOR,
  ROLE.TECNICO_FARMACIA
];

export const ROLES_CAJA: Rol[] = [
  ROLE.ADMINISTRADOR,
  ROLE.CAJERO
];

export const SOLO_ADMINISTRADOR: Rol[] = [
  ROLE.ADMINISTRADOR
];
